version: '3.7'
 
services:
 
  headless-dev:
    container_name: reactstorefront-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '443:443'
    volumes:
      - ./:/app