export const GET_ALL_OFFERS = 'GET_ALL_OFFERS'
export const SET_STEP = 'SET_STEP'

//WORDPRESS
export const SET_WORDPRESS_URI = 'SET_WORDPRESS_URI'

//M2
export const SET_M2_STEP = 'SET_M2_STEP'
export const SET_REQUEST = 'SET_REQUEST'
export const SET_ERROR = 'SET_ERROR'
export const SET_SUCCESS = 'SET_SUCCESS'
export const SET_FORM_ERROR = 'SET_FORM_ERROR'
export const SET_CART_SUCCESS = 'SET_CART_SUCCESS'
export const SET_EMPTY_CART_SUCCESS = 'SET_EMPTY_CART_SUCCESS'
export const SET_ITEM_SUCCESS = 'SET_ITEM_SUCCESS'
export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS'
export const SET_CUSTOMER_DATA_SUCCESS = 'SET_CUSTOMER_DATA_SUCCESS'
export const SET_CUSTOMER_WISHLIST_SUCCESS = 'SET_CUSTOMER_WISHLIST_SUCCESS'
export const SET_CUSTOMER_ORDER_SUCCESS = 'SET_CUSTOMER_ORDER_SUCCESS'
export const SET_PAYMENT_METHOD_OPS_SUCCESS = 'SET_PAYMENT_METHOD_OPS_SUCCESS'
export const SET_PAYMENT_URL_SUCCESS = 'SET_PAYMENT_URL_SUCCESS'
export const SET_APPLIED_COUPONS = 'SET_APPLIED_COUPONS'
export const SET_AUTH0_TOKEN = 'SET_AUTH0_TOKEN'

export const SET_SHIPPING_ADDRESS = 'SET_SHIPPING_ADDRESS'
export const SET_SHIPPING_VIEW_ADDRESS = 'SET_SHIPPING_VIEW_ADDRESS'
export const SET_BILLING_ADDRESS = 'SET_BILLING_ADDRESS'
export const SET_PAYMENT_METHOD = 'SET_PAYMENT_METHOD'
export const GET_POINT_HOP = 'GET_POINT_HOP'
export const SET_POINT_HOP = 'SET_POINT_HOP'
//USERS
export const SET_M2_LOGIN_SUCCESS = 'SET_M2_LOGIN_SUCCESS'
export const SET_AUTH0_LOGIN_SUCCESS = 'SET_AUTH0_LOGIN_SUCCESS'
export const SET_USER_REQUEST = 'SET_USER_REQUEST'
export const SET_USER_ERROR = 'SET_USER_ERROR'
export const SET_CART_AND_ITEMS_SUCCESS = 'SET_CART_AND_ITEMS_SUCCESS'
export const SET_LOGIN_REQUEST = 'SET_LOGIN_REQUEST'
export const NEW_M2_SUCCESS = 'NEW_M2_SUCCESS'
export const NEW_AUTH0_SUCCESS = 'NEW_AUTH0_SUCCESS'
export const LOGOUT = 'LOGOUT'
export const OPENTOOWEAK = 'OPENTOOWEAK'
export const AUTH0_FORGOT_PASSWORD_SUCCESS = 'AUTH0_FORGOT_PASSWORD_SUCCESS'
export const SET_REGISTRED_USER_TO_NEWSLETTER = 'SET_REGISTRED_USER_TO_NEWSLETTER'

// CLEAR ALERTS STATE REDUX
export const SET_CLEAR_ALERTS = 'SET_CLEAR_ALERTS'

//EVENTS
export const GET_ALL_EVENTS_START = 'GET_ALL_EVENTS_START'
export const GET_ALL_EVENTS_SUCCESS = 'GET_ALL_EVENTS_SUCCESS'
export const GET_ALL_EVENTS_FAIL = 'GET_ALL_EVENTS_FAIL'

//PERKS (beneficios)
export const GET_ALL_PERKS_START = 'GET_ALL_PERKS_START'
export const GET_ALL_PERKS_SUCCESS = 'GET_ALL_PERKS_SUCCESS'
export const GET_ALL_PERKS_FAIL = 'GET_ALL_PERKS_FAIL'

//PAIRINGS maridajes
export const GET_ALL_PAIRINGS_START = 'GET_ALL_PAIRINGS_START'
export const GET_ALL_PAIRINGS_SUCCESS = 'GET_ALL_PAIRINGS_SUCCESS'
export const GET_ALL_PAIRINGS_FAIL = 'GET_ALL_PAIRINGS_FAIL'

//SELECTIONS
export const GET_ALL_SELECTIONS_START = 'GET_ALL_SELECTIONS_START'
export const GET_ALL_SELECTIONS_SUCCESS = 'GET_ALL_SELECTIONS_SUCCESS'
export const GET_ALL_SELECTIONS_FAIL = 'GET_ALL_SELECTIONS_FAIL'

//
export const GET_SOCIAL_MEDIA = 'GET_SOCIAL_MEDIA'

//POSTS
export const GET_ALL_POSTS_START = 'GET_ALL_POSTS_START'
export const GET_ALL_POSTS_SUCCESS = 'GET_ALL_POSTS_SUCCESS'
export const GET_ALL_POSTS_FAIL = 'GET_ALL_POSTS_FAIL'
//SHIPPING
export const SET_SELECTED_SHIPPING_METHOD = 'SET_SELECTED_SHIPPING_METHOD'
