export const GET_ALL_OFFERS = 'GET_ALL_OFFERS'
export const SET_STEP = 'SET_STEP'

//WORDPRESS
export const SET_WORDPRESS_URI = 'SET_WORDPRESS_URI'

//M2
export const SET_M2_STEP = 'SET_M2_STEP'
export const SET_REQUEST = 'SET_REQUEST'
export const SET_ERROR = 'SET_ERROR'
export const SET_FORM_ERROR = 'SET_FORM_ERROR'
export const SET_CART_SUCCESS = 'SET_CART_SUCCESS'
export const SET_EMPTY_CART_SUCCESS = 'SET_EMPTY_CART_SUCCESS'
export const SET_ITEM_SUCCESS = 'SET_ITEM_SUCCESS'
export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS'
export const SET_CUSTOMER_DATA_SUCCESS = 'SET_CUSTOMER_DATA_SUCCESS'
export const SET_CUSTOMER_WISHLIST_SUCCESS = 'SET_CUSTOMER_WISHLIST_SUCCESS'
export const SET_CUSTOMER_ORDER_SUCCESS = 'SET_CUSTOMER_ORDER_SUCCESS'
export const SET_PAYMENT_METHOD_OPS_SUCCESS = 'SET_PAYMENT_METHOD_OPS_SUCCESS'
export const SET_PAYMENT_URL_SUCCESS = 'SET_PAYMENT_URL_SUCCESS'
export const SET_APPLIED_COUPONS = 'SET_APPLIED_COUPONS'

export const SET_SHIPPING_ADDRESS = 'SET_SHIPPING_ADDRESS'
export const SET_BILLING_ADDRESS = 'SET_BILLING_ADDRESS'
export const SET_PAYMENT_METHOD = 'SET_PAYMENT_METHOD'

//USERS
export const SET_M2_LOGIN_SUCCESS = 'SET_M2_LOGIN_SUCCESS'
export const SET_AUTH0_LOGIN_SUCCESS = 'SET_AUTH0_LOGIN_SUCCESS'
export const SET_USER_REQUEST = 'SET_USER_REQUEST'
export const SET_USER_ERROR = 'SET_USER_ERROR'
export const SET_CART_AND_ITEMS_SUCCESS = 'SET_CART_AND_ITEMS_SUCCESS'
export const SET_LOGIN_REQUEST = 'SET_LOGIN_REQUEST'
export const NEW_M2_SUCCESS = 'NEW_M2_SUCCESS'
export const NEW_AUTH0_SUCCESS = 'NEW_AUTH0_SUCCESS'
export const LOGOUT = 'LOGOUT'
